#!/usr/local/bin/expect -f

set timeout 10

# Use TERM=dumb to prevent terminal color probing which causes OSC sequences
set env(TERM) dumb

set datarobot_cli_config [lindex $argv 0]; # Grab the first command line parameter

spawn dr auth set-url --config $datarobot_cli_config

# If we get an overwrite prompt be sure to say yes to it first
expect {
    "Do you want to login with a different account" {
        send -- "y\r\n"
    }
    timeout
}

expect "Check your DataRobot login page"
send -- "https://app.datarobot.com\r\n"

expect eof
