#!/usr/local/bin/expect -f

set timeout 20

# Use TERM=dumb to prevent terminal color probing which causes OSC sequences
set env(TERM) dumb

spawn dr auth login

# If we get an prompt for needed URL be sure to set it first
expect {
    "Check your DataRobot login page" {
        send -- "https://app.datarobot.com\r\n"
    }
    timeout
}

expect "https://app.datarobot.com/account/developer-tools?cliRedirect=true"
sleep 3
# ctrl-c
send -- {^C}
expect eof
