#!/usr/local/bin/expect -f

set timeout 10

# Use TERM=dumb to prevent terminal color probing which causes OSC sequences
set env(TERM) dumb

set datarobot_cli_config [lindex $argv 0]; # Grab the first command line parameter

spawn dr auth setURL --config $datarobot_cli_config

# If we get an overwrite prompt be sure to say yes to it first
expect {
    "do you want to overwrite" {
        send -- "y\r\n"
    }
    timeout
}

expect "please enter the URL you use"
send -- "https://app.datarobot.com\r\n"

expect eof
