#!/usr/local/bin/expect -f

set timeout -1

spawn dr auth setURL

# If we get an overwrite prompt be sure to say yes to it first
expect {
    "please enter the URL you use" {
        send -- "https://testing.example.com\r\n"
    }
    "do you want to overwrite? (y/N)" {
        send -- "y\r\n"
        "please enter the URL you use" {
            send -- "https://testing.example.com\r\n"
        }
    }
}

expect eof
