// Copyright 2025 DataRobot, Inc. and its affiliates.
// All rights reserved.
// DataRobot, Inc. Confidential.
// This is unpublished proprietary source code of DataRobot, Inc.
// and its affiliates.
// The copyright notice above does not evidence any actual or intended
// publication of such source code.

package dotenv

import (
	"os"
	"strings"
	"time"

	"github.com/charmbracelet/log"
	"github.com/datarobot/cli/cmd/auth"
	"github.com/spf13/cobra"
)

var Cmd = &cobra.Command{
	Use:   "dotenv",
	Short: "Add Datarobot credentials to .env file",
	Long:  "Generate or update .env file with Datarobot credentials",
	Run:   Run,
}

var defaultEnvTemplate = `# Autogenerated by dr dotenv 

DATAROBOT_ENDPOINT=
DATAROBOT_API_TOKEN=
`

func Run(_ *cobra.Command, _ []string) {
	// fmt.Println("This is dotenv command")

	dotenvFile := ".env"
	if _, err := os.Stat(dotenvFile); err == nil {
		backupFile := dotenvFile + "." + time.Now().Format(time.RFC3339)

		err = os.Rename(dotenvFile, backupFile)
		if err != nil {
			log.Fatal(err)
		}

		log.Info("Backing up " + dotenvFile + " as " + backupFile)
	}

	f, err := os.Create(".env")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	var dotenvTemplate string

	templateFiles := []string{
		dotenvFile + ".sample",
		dotenvFile + ".template",
	}

	for _, templateFile := range templateFiles {
		if _, err := os.Stat(templateFile); err == nil {
			bytes, err := os.ReadFile(templateFile)
			if err != nil {
				log.Warn(err)
				continue
			}

			if len(bytes) > 0 {
				log.Info("Using " + templateFile + " as template")
				dotenvHeader := "# Autogenerated by dr dotenv from " + templateFile + " file\n\n"
				dotenvTemplate = dotenvHeader + string(bytes)
			}
		}
	}

	if len(dotenvTemplate) == 0 {
		dotenvTemplate = defaultEnvTemplate
	}

	for templateLine := range strings.Lines(dotenvTemplate) {
		if strings.HasPrefix(templateLine, "DATAROBOT_ENDPOINT=") {
			datarobotEndpoint, err := auth.GetURL(false)
			if err == nil {
				log.Info("Adding DATAROBOT_ENDPOINT")

				_, _ = f.WriteString("DATAROBOT_ENDPOINT=" + datarobotEndpoint + "\n")
			}
		} else if strings.HasPrefix(templateLine, "DATAROBOT_API_TOKEN=") {
			datarobotAPIToken, err := auth.GetAPIKey()
			if err == nil {
				log.Info("Adding DATAROBOT_API_TOKEN")

				_, _ = f.WriteString("DATAROBOT_API_TOKEN=" + datarobotAPIToken + "\n")
			}
		} else {
			_, _ = f.WriteString(templateLine)
		}
	}
}
