version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "⬆️ SEC(Deps): "

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "⬆️ CI(Actions): "
