version: "2"
run:
  go: 1.25.7
linters:
  enable:
    - asasalint
    - bodyclose
    - contextcheck
    - cyclop
    - dupword
    - errname
    - exhaustive
    - loggercheck
    - misspell
    - nestif
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - testifylint
    - unconvert
    - usestdlibvars
    - wsl_v5
  settings:
    revive:
      rules:
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#error-strings
        - name: error-strings
          severity: warning
          disabled: true
          exclude: [""]
          arguments:
            - "xerrors.New"
    staticcheck:
      checks: [ "all", "-ST1005"]
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
        - defers
        - atomic
        - nilfunc
        - printf
        - sortslice
        - tests
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
