version: "2"
run:
  go: 1.24.7
linters:
  enable:
    - asasalint
    - bodyclose
    - contextcheck
    - cyclop
    - dupword
    - errname
    - exhaustive
    - loggercheck
    - misspell
    - nestif
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - testifylint
    - unconvert
    - usestdlibvars
    - wsl_v5
  settings:
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
        - defers
        - atomic
        - nilfunc
        - printf
        - sortslice
        - tests
    revive:
      rules:
        - name: var-naming
          arguments:
            - ["misc"]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: internal/misc/
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
