header:
  license:
    spdx-id: N/A
    copyright-owner: N/A
    content: |-
      Copyright 2025 DataRobot, Inc. and its affiliates.
      All rights reserved.
      DataRobot, Inc. Confidential.
      This is unpublished proprietary source code of DataRobot, Inc.
      and its affiliates.
      The copyright notice above does not evidence any actual or intended
      publication of such source code.
  paths:
    - 'cmd/'
    - 'internal/'
    - 'testutils/'
    - 'tools/'
    - 'main.go'
    - 'internal/task/Taskfile.tmpl.yaml'

  paths-ignore:
    - 'internal/db/model/'

  comment: on-failure