# Wolfi-based, minimal, nonroot equivalent of distroless/static. Digest captured 2026-07-22.
FROM cgr.dev/chainguard/static:latest@sha256:60582b2ae6074f641094af0f370d4ab241aab271858a66223dcde7eee9f51638

ARG TARGETPLATFORM
COPY $TARGETPLATFORM/dr /dr

ENTRYPOINT ["/dr"]
