name: Setup Environment

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go version to use'
        required: false
        type: string
        default: '1.26.4'
      install-taskfile:
        description: 'Whether to install Taskfile'
        required: false
        type: boolean
        default: true
      setup-cache:
        description: 'Whether to setup Go cache'
        required: false
        type: boolean
        default: false

# S5: deny all by default; jobs opt-in to what they need.
permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write   # actions/cache (save)
    steps:
      - name: Checkout Code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: Install Taskfile
        if: inputs.install-taskfile
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go Cache
        if: inputs.setup-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
            bin
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
