name: Review Router

on:
  pull_request_target:
    types: [labeled, opened, closed]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

jobs:
  route:
    uses: datarobot-oss/.github/.github/workflows/review-router.yml@main
    secrets: inherit
